### ISSUE TITLE
Exception: Could not determine engine root path

### ISSUE THREAD

**Issue by keithoconor** [twistedbytes-net/rider-unreal_genproj#2]
I just tried this plugin (v1.0.3, with Rider 2022.2) and got the exception below. This is with the latest launcher version of Unreal (5.0.3), installed at `C:\Program Files\Epic Games\UE_5.0`.

> java.lang.Throwable: Could not determine engine root path.
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
> 	at net.twistedbytes.rider.plugins.unreal_genproj.actions.GenerateProjectFiles.runBlockingAction(GenerateProjectFiles.java:110)
> 	at net.twistedbytes.rider.plugins.unreal_genproj.actions.GenerateProjectFiles$1.run(GenerateProjectFiles.java:61)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
> 	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:307)
> 	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:307)
> 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
> 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
> 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by XTREME1738** [comment]
same error any updates on this?

**Comment by EncryptedNomad** [comment]
Same here, Using a source build. Are you two also on source?

**Comment by romerogames-keith** [comment]
No, haven't tried with source yet - that was with the prebuilt version that is downloaded via the Epic Launcher.

**Comment by XTREME1738** [comment]
> Same here, Using a source build. Are you two also on source?

yep on source
